export const type = {
  UPDATE_CARDS: 'UPDATE_CARDS',
  SET_GRID_SLOTS: 'SET_GRID_SLOTS',
  INIT_GAME: 'INIT_GAME',
  SET_WIN: 'SET_WIN',
  SET_WAIT: 'SET_WAIT',
  INCREASE_MOVE_COUNT: 'INCREASE_MOVE_COUNT',
  INCREASE_MATCHED_COUNT: 'INCREASE_MATCHED_COUNT',
  DECREASE_MATCHED_COUNT: 'DECREASE_MATCHED_COUNT',
  RESTART_GAME: 'RESTART_GAME',
};
