export const type = {
  UPDATE_CARDS: 'UPDATE_CARDS',
  SET_GRID_SLOTS: 'SET_GRID_SLOTS',
  INIT_GAME: 'INIT_GAME',
  SET_WIN: 'SET_WIN',
  SET_WAIT: 'SET_WAIT',
  INCREASE_MOVE_COUNT: 'INCREASE_MOVE_COUNT',
  INCREASE_MATCH_COUNT: 'INCREASE_MATCH_COUNT',
  DECREASE_MATCH_COUNT: 'DECREASE_MATCH_COUNT',
  RESTART_GAME: 'RESTART_GAME',
  SET_GAME_LEVEL: 'SET_GAME_LEVEL',
  SET_GO_SHIFT: 'SET_GO_SHIFT',
  SET_DIRECTION: 'SET_DIRECTION',
};
